# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

src/hygra-test.dir/test.c.o: ../src/libhygra/../bstrlib/bstrlib.h
src/hygra-test.dir/test.c.o: ../src/libhygra/hygra.h
src/hygra-test.dir/test.c.o: ../src/libhygra/test.c

