.PHONY: clean All

All:
	@echo "----------Building project:[ termtrees - Debug ]----------"
	$(MAKE) -C "termtrees" -f "termtrees.mk"
clean:
	@echo "----------Cleaning project:[ termtrees - Debug ]----------"
	$(MAKE) -C "termtrees" -f "termtrees.mk" clean
