# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

src/termtrees-test.dir/cli.c.o: ../src/bstrlib/bstrlib.h
src/termtrees-test.dir/cli.c.o: ../src/cli.c
src/termtrees-test.dir/cli.c.o: ../src/libhygra/hygra.h
src/termtrees-test.dir/cli.c.o: ../src/termtrees.h

src/termtrees-test.dir/op_signature.c.o: ../src/bstrlib/bstrlib.h
src/termtrees-test.dir/op_signature.c.o: ../src/libhygra/hygra.h
src/termtrees-test.dir/op_signature.c.o: ../src/op_signature.c
src/termtrees-test.dir/op_signature.c.o: ../src/termtrees.h

src/termtrees-test.dir/terms.c.o: ../src/bstrlib/bstrlib.h
src/termtrees-test.dir/terms.c.o: ../src/libhygra/hygra.h
src/termtrees-test.dir/terms.c.o: ../src/terms.c
src/termtrees-test.dir/terms.c.o: ../src/termtrees.h

src/termtrees-test.dir/termtrees.c.o: ../src/bstrlib/bstrlib.h
src/termtrees-test.dir/termtrees.c.o: ../src/libhygra/hygra.h
src/termtrees-test.dir/termtrees.c.o: ../src/termtrees.c
src/termtrees-test.dir/termtrees.c.o: ../src/termtrees.h

src/termtrees-test.dir/test.c.o: ../src/bstrlib/bstrlib.h
src/termtrees-test.dir/test.c.o: ../src/libhygra/hygra.h
src/termtrees-test.dir/test.c.o: ../src/termtrees.h
src/termtrees-test.dir/test.c.o: ../src/test.c

