C formal concept analysis library: src/fca/common/measurement.c File Reference
src/fca/common/measurement.c File Reference
measurement.c, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
#include <math.h>
#include "../common.h"
Functions
EtaFunction newEtaFunction (size_t types, size_t measurements, size_t constants)
creates a new EtaFunction
void deleteEtaFunction (EtaFunction *eta)
deletes an EtaFunction and sets the pointer to zero
EtaFunction newUniformEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the same constant for each type
EtaFunction newGeneralEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the a constant for each type and measurement on its own
CommutativeProduct newCommutativeProduct (size_t constants)
creates a new commutative product without any factors
void deleteCommutativeProduct (CommutativeProduct *p)
deletes a CommutativeProduct and sets its pointer to zero.
ConditionMap newConditionMap (size_t objects)
creates a new condition map
void deleteConditionMap (ConditionMap *c)
deletes a ConditionMap object
LogCache newLogCache (size_t constants)
creates a new cache for logs of constants
void deleteLogCache (LogCache *log_c)
deletes a LogCache and sets its pointer to zero
void calculateLogs (const EtaFunction eta, LogCache log_c)
calculates the logarithms of probabilities given by constants, and their complements
Detailed Description
measurement.c, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. This file contains implementations regarding measurement error probabilities related structures operations
Definition in file measurement.c.
Function Documentation
void calculateLogs (const EtaFunction eta, LogCache log_c)
calculates the logarithms of probabilities given by constants, and their complements
Parameters:
eta input constants
log_c output structure to update the constants
Definition at line 235 of file measurement.c.
References sEtaFunction::C, sEtaFunction::constants, sLogCache::constants, sLogCache::logC, sLogCache::logNotC, and WARN_IF_UNEQUAL_DO.
Referenced by main().
{
    WARN_IF_UNEQUAL_DO(eta->constants, log_c->constants, return);
    /*
     * we could use just any logarithm, so 2 seems reasonable...
     */
    for (size_t i = 0; i < eta->constants; ++i)
    {
        log_c->logC[i] = log2(eta->C[i]);
        log_c->logNotC[i] = log2(1. - eta->C[i]);
    }
}
void deleteCommutativeProduct (CommutativeProduct * p)
deletes a CommutativeProduct and sets its pointer to zero.
Parameters:
p
Definition at line 146 of file measurement.c.
References RETURN_IF_ZERO.
{
    RETURN_IF_ZERO(p);
    RETURN_IF_ZERO(*p);
    free((*p)->match);
    free((*p)->mismatch);
    free(*p);
    *p = 0;
}
void deleteConditionMap (ConditionMap * c)
deletes a ConditionMap object
Parameters:
c
Definition at line 182 of file measurement.c.
References RETURN_IF_ZERO.
{
    RETURN_IF_ZERO(c);
    RETURN_IF_ZERO(*c);
    free((*c)->c);
    free(*c);
    *c = 0;
}
void deleteEtaFunction (EtaFunction * eta)
deletes an EtaFunction and sets the pointer to zero
Parameters:
eta
Definition at line 61 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by main().
{
    RETURN_IF_ZERO(eta);
    RETURN_IF_ZERO(*eta);
    free((*eta)->C);
    free((*eta)->eta);
    free(*eta);
    *eta = 0;
}
void deleteLogCache (LogCache * log_c)
deletes a LogCache and sets its pointer to zero
Parameters:
log_c
Definition at line 217 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by main().
{
    RETURN_IF_ZERO(log_c);
    RETURN_IF_ZERO(*log_c);
    free((*log_c)->logC);
    free((*log_c)->logNotC);
    free(*log_c);
    *log_c = 0;
}
CommutativeProduct newCommutativeProduct (size_t constants)
creates a new commutative product without any factors
Parameters:
constants number of formal constants
Returns:
new CommutativeProduct object
Definition at line 125 of file measurement.c.
References sCommutativeProduct::constants, sCommutativeProduct::match, sCommutativeProduct::mismatch, and RETURN_ZERO_IF_ZEROI.
{
    RETURN_ZERO_IF_ZEROI(constants);
    CommutativeProduct p;
    p = malloc(sizeof(struct sCommutativeProduct));
    p->constants = constants;
    p->mismatch = calloc(constants, sizeof(size_t));
    p->match = calloc(constants, sizeof(size_t));
    return p;
}
ConditionMap newConditionMap (size_t objects)
creates a new condition map
Parameters:
objects cardinality of the domain
Returns:
new ConditionMap object
Definition at line 164 of file measurement.c.
References sConditionMap::c, sConditionMap::objects, and RETURN_ZERO_IF_ZEROI.
{
    RETURN_ZERO_IF_ZEROI(objects);
    ConditionMap c;
    c = malloc(sizeof(struct sConditionMap));
    c->objects = objects;
    c->c = calloc(objects, sizeof(size_t));
    return c;
}
EtaFunction newEtaFunction (size_t types, size_t measurements, size_t constants)
creates a new EtaFunction
Parameters:
types number of types, usually 2
measurements number of different measurements,
constants number of different error constants, <= types*measurements are needed.
Returns:
a new structure
Definition at line 37 of file measurement.c.
References sEtaFunction::C, sEtaFunction::constants, sEtaFunction::eta, sEtaFunction::measurements, RETURN_ZERO_IF_ZEROI, and sEtaFunction::types.
Referenced by newGeneralEtaFunction(), and newUniformEtaFunction().
{
    RETURN_ZERO_IF_ZEROI(types);
    RETURN_ZERO_IF_ZEROI(measurements);
    RETURN_ZERO_IF_ZEROI(constants);
    EtaFunction e;
    e = malloc(sizeof(struct sEtaFunction));
    e->types = types;
    e->measurements = measurements;
    e->constants = constants;
    e->C = calloc(constants, sizeof(Probability));
    e->eta = calloc(types * measurements, sizeof(size_t));
    return e;
}
EtaFunction newGeneralEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the a constant for each type and measurement on its own
Parameters:
types
measurements
Returns:
Definition at line 103 of file measurement.c.
References sEtaFunction::eta, and newEtaFunction().
{
    EtaFunction e;
    e = newEtaFunction(types, measurements, types * measurements);
    for (size_t t = 0; t < types; ++t)
    {
        for (size_t m = 0; m < measurements; ++m)
        {
            e->eta[t * measurements + m] = t * measurements + m;
        }
    }
    return e;
}
LogCache newLogCache (size_t constants)
creates a new cache for logs of constants
Parameters:
constants number of constants
Returns:
new LogCache
Definition at line 199 of file measurement.c.
References sLogCache::constants, sLogCache::logC, and sLogCache::logNotC.
Referenced by main().
{
    LogCache l;
    l = malloc(sizeof(struct sLogCache));
    l->constants = constants;
    l->logC = calloc(constants, sizeof(LogProbability));
    l->logNotC = calloc(constants, sizeof(LogProbability));
    return l;
}
EtaFunction newUniformEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the same constant for each type
Parameters:
types
measurements
Returns:
Definition at line 80 of file measurement.c.
References sEtaFunction::eta, and newEtaFunction().
Referenced by main().
{
    EtaFunction e;
    e = newEtaFunction(types, measurements, types);
    for (size_t t = 0; t < types; ++t)
    {
        for (size_t m = 0; m < measurements; ++m)
        {
            e->eta[t * measurements + m] = t;
        }
    }
    return e;
}