C formal concept analysis library: src/fca/common/measurement.h File Reference
src/fca/common/measurement.h File Reference
#include <stdlib.h>
#include <float.h>
#include <math.h>
Data Structures
struct sEtaFunction
this structure contains information on how many cases for measurements there are, and what the probabilities of erroneous measurement there is for each case
struct sCommutativeProduct
This struct represents a formal product of formal constants x_i and their counterparts (1-x_i) under the assumption of communtativity of the product.
struct sConditionMap
This struct represents a map between the object sets of two formal contexts.
struct sLogCache
This structure stores the logarithms of probabilities and of their complements.
Defines
#define LOG_PROB_LOWER_BOUND (-INFINITY)
#define LOG_PROB_UPPER_BOUND (1.)
Typedefs
typedef double Probability
measurement.h, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
typedef double LogProbability
typedef struct sEtaFunction * EtaFunction
this structure contains information on how many cases for measurements there are, and what the probabilities of erroneous measurement there is for each case
typedef struct
sCommutativeProduct * CommutativeProduct
This struct represents a formal product of formal constants x_i and their counterparts (1-x_i) under the assumption of communtativity of the product.
typedef struct sConditionMap * ConditionMap
This struct represents a map between the object sets of two formal contexts.
typedef struct sLogCache * LogCache
This structure stores the logarithms of probabilities and of their complements.
Functions
EtaFunction newEtaFunction (size_t types, size_t measurements, size_t constants)
creates a new EtaFunction
EtaFunction newUniformEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the same constant for each type
EtaFunction newGeneralEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the a constant for each type and measurement on its own
void deleteEtaFunction (EtaFunction *eta)
deletes an EtaFunction and sets the pointer to zero
CommutativeProduct newCommutativeProduct (size_t constants)
creates a new commutative product without any factors
void deleteCommutativeProduct (CommutativeProduct *p)
deletes a CommutativeProduct and sets its pointer to zero.
ConditionMap newConditionMap (size_t objects)
creates a new condition map
void deleteConditionMap (ConditionMap *c)
deletes a ConditionMap object
LogCache newLogCache (size_t constants)
creates a new cache for logs of constants
void deleteLogCache (LogCache *log_c)
deletes a LogCache and sets its pointer to zero
void calculateLogs (const EtaFunction eta, LogCache log_c)
calculates the logarithms of probabilities given by constants, and their complements
LogProbability logProbabilityFromProduct (const LogCache log_c, CommutativeProduct l)
calculate the log probability from a power vector
LogProbability sumUp (const LogProbability *restrict V, size_t length, LogProbability lower_bound, LogProbability upper_bound)
This routine calculates the sum of elements of a vector.
Define Documentation
#define LOG_PROB_LOWER_BOUND (-INFINITY)
Definition at line 33 of file measurement.h.
Referenced by logProbabilityFromProduct(), and optimizeConditionMap().
#define LOG_PROB_UPPER_BOUND (1.)
Definition at line 34 of file measurement.h.
Referenced by logProbabilityFromProduct().
Typedef Documentation
typedef struct sCommutativeProduct* CommutativeProduct
This struct represents a formal product of formal constants x_i and their counterparts (1-x_i) under the assumption of communtativity of the product.
E.g.
typedef struct sConditionMap* ConditionMap
This struct represents a map between the object sets of two formal contexts.
typedef struct sEtaFunction* EtaFunction
this structure contains information on how many cases for measurements there are, and what the probabilities of erroneous measurement there is for each case
typedef struct sLogCache* LogCache
This structure stores the logarithms of probabilities and of their complements.
We use logarithms to the base 2.
typedef double LogProbability
Definition at line 31 of file measurement.h.
typedef double Probability
measurement.h, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. type for probabilities
Definition at line 30 of file measurement.h.
Function Documentation
void calculateLogs (const EtaFunction eta, LogCache log_c)
calculates the logarithms of probabilities given by constants, and their complements
Parameters:
eta input constants
log_c output structure to update the constants
Definition at line 239 of file measurement.c.
References sEtaFunction::C, sEtaFunction::constants, sLogCache::constants, sLogCache::logC, sLogCache::logNotC, and WARN_IF_UNEQUAL_DO.
Referenced by main().
{
    WARN_IF_UNEQUAL_DO(eta->constants, log_c->constants, return);
    /*
     * we could use just any logarithm, so 2 seems reasonable...
     */
    for (size_t i = 0; i < eta->constants; ++i)
    {
        log_c->logC[i] = log2(eta->C[i]);
        log_c->logNotC[i] = log2(1. - eta->C[i]);
    }
}
void deleteCommutativeProduct (CommutativeProduct * p)
deletes a CommutativeProduct and sets its pointer to zero.
Parameters:
p
Definition at line 149 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by optimizeConditionMap().
{
    RETURN_IF_ZERO(p);
    RETURN_IF_ZERO(*p);
    free((*p)->match);
    free((*p)->mismatch);
    free((*p)->intermediate);
    free(*p);
    *p = 0;
}
void deleteConditionMap (ConditionMap * c)
deletes a ConditionMap object
Parameters:
c
Definition at line 186 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by main().
{
    RETURN_IF_ZERO(c);
    RETURN_IF_ZERO(*c);
    free((*c)->c);
    free(*c);
    *c = 0;
}
void deleteEtaFunction (EtaFunction * eta)
deletes an EtaFunction and sets the pointer to zero
Parameters:
eta
Definition at line 62 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by main().
{
    RETURN_IF_ZERO(eta);
    RETURN_IF_ZERO(*eta);
    free((*eta)->C);
    free((*eta)->eta);
    free(*eta);
    *eta = 0;
}
void deleteLogCache (LogCache * log_c)
deletes a LogCache and sets its pointer to zero
Parameters:
log_c
Definition at line 221 of file measurement.c.
References RETURN_IF_ZERO.
Referenced by main().
{
    RETURN_IF_ZERO(log_c);
    RETURN_IF_ZERO(*log_c);
    free((*log_c)->logC);
    free((*log_c)->logNotC);
    free(*log_c);
    *log_c = 0;
}
LogProbability logProbabilityFromProduct (const LogCache log_c, CommutativeProduct l)
calculate the log probability from a power vector
Parameters:
log_c logarithms of constants
l vector of constant and complementary powers
Returns:
the log probability of the product given by the vector of powers, l
Definition at line 261 of file measurement.c.
References sCommutativeProduct::constants, sLogCache::constants, sCommutativeProduct::intermediate, LOG_PROB_LOWER_BOUND, LOG_PROB_UPPER_BOUND, sLogCache::logC, sLogCache::logNotC, sCommutativeProduct::match, sCommutativeProduct::mismatch, RETURN_ZERO_IF_ZERO, sumUp(), and WARN_IF_UNEQUAL_DO.
Referenced by optimizeConditionMap().
{
    RETURN_ZERO_IF_ZERO(log_c);
    RETURN_ZERO_IF_ZERO(l);
    WARN_IF_UNEQUAL_DO(log_c->constants, l->constants, return 0);
    size_t constants = log_c->constants;
    for (size_t c = 0; c < constants; ++c)
    {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
        /*
         * 0*-inf is still -inf; but we want to enforce 0*-inf = 0
         */
        if (l->match[c] > 0)
            l->intermediate[c] = log_c->logNotC[c] * (LogProbability) l->match[c];
        else
            l->intermediate[c] = 0.;
        if (l->mismatch[c] > 0)
            l->intermediate[c + constants] = log_c->logC[c]
                    * (LogProbability) l->mismatch[c];
        else
            l->intermediate[c + constants] = 0.;
#pragma GCC diagnostic pop
    }
    return sumUp(l->intermediate, constants * 2, LOG_PROB_LOWER_BOUND,
    LOG_PROB_UPPER_BOUND);
}
CommutativeProduct newCommutativeProduct (size_t constants)
creates a new commutative product without any factors
Parameters:
constants number of formal constants
Returns:
new CommutativeProduct object
Definition at line 126 of file measurement.c.
References sCommutativeProduct::constants, sCommutativeProduct::intermediate, sCommutativeProduct::match, sCommutativeProduct::mismatch, and RETURN_ZERO_IF_ZEROI.
Referenced by optimizeConditionMap().
{
    RETURN_ZERO_IF_ZEROI(constants);
    CommutativeProduct p;
    p = malloc(sizeof(struct sCommutativeProduct));
    p->constants = constants;
    p->mismatch = calloc(constants, sizeof(size_t));
    p->match = calloc(constants, sizeof(size_t));
    p->intermediate = malloc(constants * 2 * sizeof(LogProbability));
    return p;
}
ConditionMap newConditionMap (size_t objects)
creates a new condition map
Parameters:
objects cardinality of the domain
Returns:
new ConditionMap object
Definition at line 168 of file measurement.c.
References sConditionMap::c, sConditionMap::objects, and RETURN_ZERO_IF_ZEROI.
Referenced by main(), and newFakeMeasurement().
{
    RETURN_ZERO_IF_ZEROI(objects);
    ConditionMap c;
    c = malloc(sizeof(struct sConditionMap));
    c->objects = objects;
    c->c = calloc(objects, sizeof(size_t));
    return c;
}
EtaFunction newEtaFunction (size_t types, size_t measurements, size_t constants)
creates a new EtaFunction
Parameters:
types number of types, usually 2
measurements number of different measurements,
constants number of different error constants, <= types*measurements are needed.
Returns:
a new structure
Definition at line 38 of file measurement.c.
References sEtaFunction::C, sEtaFunction::constants, sEtaFunction::eta, sEtaFunction::measurements, RETURN_ZERO_IF_ZEROI, and sEtaFunction::types.
Referenced by newGeneralEtaFunction(), and newUniformEtaFunction().
{
    RETURN_ZERO_IF_ZEROI(types);
    RETURN_ZERO_IF_ZEROI(measurements);
    RETURN_ZERO_IF_ZEROI(constants);
    EtaFunction e;
    e = malloc(sizeof(struct sEtaFunction));
    e->types = types;
    e->measurements = measurements;
    e->constants = constants;
    e->C = calloc(constants, sizeof(Probability));
    e->eta = calloc(types * measurements, sizeof(size_t));
    return e;
}
EtaFunction newGeneralEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the a constant for each type and measurement on its own
Parameters:
types
measurements
Returns:
Definition at line 104 of file measurement.c.
References sEtaFunction::eta, and newEtaFunction().
{
    EtaFunction e;
    e = newEtaFunction(types, measurements, types * measurements);
    for (size_t t = 0; t < types; ++t)
    {
        for (size_t m = 0; m < measurements; ++m)
        {
            e->eta[t * measurements + m] = t * measurements + m;
        }
    }
    return e;
}
LogCache newLogCache (size_t constants)
creates a new cache for logs of constants
Parameters:
constants number of constants
Returns:
new LogCache
Definition at line 203 of file measurement.c.
References sLogCache::constants, sLogCache::logC, and sLogCache::logNotC.
Referenced by main().
{
    LogCache l;
    l = malloc(sizeof(struct sLogCache));
    l->constants = constants;
    l->logC = calloc(constants, sizeof(LogProbability));
    l->logNotC = calloc(constants, sizeof(LogProbability));
    return l;
}
EtaFunction newUniformEtaFunction (size_t types, size_t measurements)
create a new EtaFunction with the same constant for each type
Parameters:
types
measurements
Returns:
Definition at line 81 of file measurement.c.
References sEtaFunction::eta, and newEtaFunction().
Referenced by main().
{
    EtaFunction e;
    e = newEtaFunction(types, measurements, types);
    for (size_t t = 0; t < types; ++t)
    {
        for (size_t m = 0; m < measurements; ++m)
        {
            e->eta[t * measurements + m] = t;
        }
    }
    return e;
}
LogProbability sumUp (const LogProbability *restrict V, size_t length, LogProbability lower_bound, LogProbability upper_bound)
This routine calculates the sum of elements of a vector.
Parameters:
V ptr to array of LogProbabilities
length length of array V
lower_bound lower bound to include in this sum
upper_bound upper bound to include in this sum
Returns:
Definition at line 304 of file measurement.c.
Referenced by logProbabilityFromProduct().
{
    //TODO: Make this routine smarter with respect to LARGE sums
    LogProbability sum;
    sum = 0.;
    for (size_t i = 0; i < length; ++i)
    {
        LogProbability summand;
        summand = V[i];
        if ((lower_bound <= summand) && (summand < upper_bound))
        {
            //printf("+%.2f",summand);
            sum += summand;
        }
    }
    //printf("=");
    return sum;
}