C formal concept analysis: src/fca_private.h File Reference
src/fca_private.h File Reference
fca_private.h, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
#include "fca_structs.h"
Functions
myFormalConceptIntentChunk * newConceptChunk (int attributes)
create a new formal concept chunk
void deleteConceptChunk (myFormalConceptIntentChunk **c)
deletes a concept chunk object and sets its pointer to zero
FormalConceptIntentBulkList newConceptBulk (int attributes)
creates a new formal concept intent bulk list
FormalConceptIntentBulkList newConceptBulkFromContext (FormalContext ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
void writeConceptsToFile (FormalContext ctx, FormalConceptIntentBulkList root, const char *filename)
write a list of concept intents into a .cxt file
void deleteConceptBulk (FormalConceptIntentBulkList *rootNode)
deletes the entire bulk list
int countConceptsInBulk (FormalConceptIntentBulkList root)
use this for bulks that are filled in order
FormalConceptIntentBulkList addConceptToBulk (FormalConceptIntentBulkList root, const IncidenceCell *intent)
copies the given intent to the bulk denoted by the root node.
void closeIntent (FormalContext ctx, const IncidenceCell *input, IncidenceCell *output)
close an attribute set, i.e.
void closeIntent2 (FormalContext ctx, const IncidenceCell *input, IncidenceCell *outputIntent, IncidenceCell *outputExtent)
close an attribute set, i.e.
int intentCmp (int attributes, const IncidenceCell *minus, const IncidenceCell *plus)
compare two intent vectors
void closeIntentV (FormalContextV ctx, const IncidenceVector input, IncidenceVector output)
close an attribute set, i.e.
int intentCmpV (size_t attributes, const IncidenceVector minus, const IncidenceVector plus)
compare two intent vectors
myFormalConceptIntentChunkV * newConceptChunkV (size_t attributes)
create a new formal concept chunk
void deleteConceptChunkV (myFormalConceptIntentChunkV **c)
deletes a concept chunk object and sets its pointer to zero
FormalConceptIntentBulkListV newConceptBulkV (size_t attributes)
creates a new formal concept intent bulk list
FormalConceptIntentBulkListV newConceptBulkFromContextV (FormalContextV ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
void writeConceptsToFileV (FormalContextV ctx, FormalConceptIntentBulkListV root, const char *filename)
write a list of concept intents into a .cxt file
void deleteConceptBulkV (FormalConceptIntentBulkListV *rootNode)
deletes the entire bulk list
size_t countConceptsInBulkV (FormalConceptIntentBulkListV root)
use this for bulks that are filled in order
FormalConceptIntentBulkListV addConceptToBulkV (FormalConceptIntentBulkListV root, const IncidenceVector intent)
copies the given intent to the bulk denoted by the root node.
FormalConceptIntentBulkListV nextClosureVX1 (FormalContextV ctx, const IncidenceVector start, const IncidenceVector stop)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm, that are in a given lexicographic interval of the powerset
FormalConceptIntentBulkListV nextClosureVX (FormalContextV ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
Detailed Description
fca_private.h, (c) 2013, Immanuel Albrecht; Dresden University of Technology, Professur für die Psychologie des Lernen und Lehrens
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
this file contains forward declarations for fca related functions that are not part of the public interface
Definition in file fca_private.h.
Function Documentation
FormalConceptIntentBulkList addConceptToBulk (FormalConceptIntentBulkList root, const IncidenceCell * intent)
copies the given intent to the bulk denoted by the root node.
Parameters:
root root node of the bulk
intent read-only pointer to an array of IncidenceCell[root->attributes]
Returns:
the node where the intent was added to the last chunk
Definition at line 428 of file fca.c.
References sFormalConceptIntentBulkNode::attributes, BULKSIZE, CELL, sFormalConceptIntentBulkNode::chunks, CHUNKSIZE, newConceptBulk(), newConceptChunk(), sFormalConceptIntentBulkNode::next, RETURN_ZERO_IF_ZERO, smyFormalConceptIntentChunk::size, and sFormalConceptIntentBulkNode::size.
Referenced by newConceptBulkFromContext().
{
    RETURN_ZERO_IF_ZERO(root);
    do
    {
        if (root->size == 0)
        {
            root->chunks[0] = newConceptChunk(root->attributes);
            root->size = 1;
        }
        int last_index;
        last_index = root->size - 1;
        if (root->chunks[last_index]->size == CHUNKSIZE)
        {
            if (root->size == BULKSIZE)
            {
                if (root->next == 0)
                {
                    root->next = newConceptBulk(root->attributes);
                }
                root = root->next;
                continue;
            }
            else
            {
                last_index = root->size++;
                root->chunks[last_index] = newConceptChunk(root->attributes);
            }
        }
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
        memcpy(
                &(CELL(root->chunks[last_index]->size, root->chunks[last_index],0)),
                intent, sizeof(IncidenceCell) * root->attributes);
#pragma GCC diagnostic pop
        root->chunks[last_index]->size++;
        break;
    } while (1);
    return root;
}
FormalConceptIntentBulkListV addConceptToBulkV (FormalConceptIntentBulkListV root, const IncidenceVector intent)
copies the given intent to the bulk denoted by the root node.
Parameters:
root root node of the bulk
intent read-only pointer to an array of IncidenceCell[root->attributes]
Returns:
the node where the intent was added to the last chunk
Definition at line 837 of file fcaV.c.
References sFormalConceptIntentBulkNodeV::attributes, BULKSIZEV, sFormalConceptIntentBulkNodeV::chunks, CHUNKSIZEV, newConceptBulkV(), newConceptChunkV(), sFormalConceptIntentBulkNodeV::next, RETURN_ZERO_IF_ZERO, ROW, smyFormalConceptIntentChunkV::size, sFormalConceptIntentBulkNodeV::size, and sFormalConceptIntentBulkNodeV::width.
Referenced by newConceptBulkFromContextV(), and nextClosureVX1().
{
    RETURN_ZERO_IF_ZERO(root);
    do
    {
        if (root->size == 0)
        {
            root->chunks[0] = newConceptChunkV(root->attributes);
            root->size = 1;
        }
        size_t last_index;
        last_index = root->size - 1;
        if (root->chunks[last_index]->size == CHUNKSIZEV)
        {
            if (root->size == BULKSIZEV)
            {
                if (root->next == 0)
                {
                    root->next = newConceptBulkV(root->attributes);
                }
                root = root->next;
                continue;
            }
            else
            {
                last_index = root->size++;
                root->chunks[last_index] = newConceptChunkV(root->attributes);
            }
        }
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
        memcpy( ROW(root->chunks[last_index]->size, root->chunks[last_index]),
                intent, sizeof(uint64_t) * root->width);
#pragma GCC diagnostic pop
        root->chunks[last_index]->size++;
        break;
    } while (1);
    return root;
}
void closeIntent (FormalContext ctx, const IncidenceCell * input, IncidenceCell * output)
close an attribute set, i.e.
add further attributes
Parameters:
ctx formal context
input the intent set that is to be closed
output the closure intent'' wrt. ctx
Definition at line 538 of file fca.c.
References smyFormalContext::attributes, CLEAR, CROSS, gIm, INCIDES, and smyFormalContext::objects.
Referenced by countContextConcepts(), and newConceptBulkFromContext().
{
    myFormalContext* I;
    I = (myFormalContext*) ctx;
    for (int var = 0; var < I->attributes; ++var)
    {
        CROSS(output[var]);
    }
    for (int g = 0; g < I->objects; ++g)
    {
        int good;
        good = 1;
        for (int m = 0; m < I->attributes; ++m)
        {
            if (INCIDES(input[m]))
                if (!gIm(g,I,m))
                {
                    /*
                     * some attribute is not present for this object -> next object
                     */
                    good = 0;
                    break;
                }
        }
        if (good)
            /*
             * remove attributes that are not common among all objects that have the input
             * attributes
             */
            for (int m = 0; m < I->attributes; ++m)
            {
                if (!gIm(g,I,m))
                {
                    CLEAR(output[m]);
                }
            }
    }
}
void closeIntent2 (FormalContext ctx, const IncidenceCell * input, IncidenceCell * outputIntent, IncidenceCell * outputExtent)
close an attribute set, i.e.
add further attributes, 1.92 times slower than closeIntent
Parameters:
ctx formal context
input the intent set that is to be closed
outputIntent the closure intent'' wrt. ctx
outputObjects the corresponding objects, i.e. intent' wrt. ctx
Definition at line 491 of file fca.c.
References smyFormalContext::attributes, CLEAR, CROSS, gIm, INCIDES, and smyFormalContext::objects.
Referenced by countContextConcepts2().
{
    myFormalContext* I;
    I = (myFormalContext*) ctx;
    for (int g = 0; g < I->objects; ++g)
    {
        CROSS(outputExtent[g]);
        for (int m = 0; m < I->attributes; ++m)
        {
            if (INCIDES(input[m]))
                if (!gIm(g,I,m))
                {
                    /*
                     * some attribute is not present for this object -> next object
                     */
                    CLEAR(outputExtent[g]);
                    break;
                }
        }
    }
    for (int m = 0; m < I->attributes; ++m)
    {
        CROSS(outputIntent[m]);
        for (int g = 0; g < I->objects; ++g)
        {
            if (INCIDES(outputExtent[g]))
                if (!gIm(g,I,m))
                {
                    CLEAR(outputIntent[m]);
                    break;
                }
        }
    }
}
void closeIntentV (FormalContextV ctx, const IncidenceVector input, IncidenceVector output)
close an attribute set, i.e.
add further attributes
Parameters:
ctx formal context
input the intent set that is to be closed
output the closure intent'' wrt. ctx
some attribute is not present for this object -> next object
remove attributes that are not common among all objects that have the input attributes
Definition at line 413 of file fcaV.c.
References smyFormalContextV::attributes, MASKVECTOR, smyFormalContextV::objects, ROW, and smyFormalContextV::width.
Referenced by countContextConceptsV(), newConceptBulkFromContextV(), and nextClosureVX1().
{
    myFormalContextV* I;
    I = (myFormalContextV*) ctx;
    for (size_t var = 0; var < I->width; ++var)
    {
        output[var] = ~0ULL;
    }
    MASKVECTOR(output, I->attributes);
    for (size_t g = 0; g < I->objects; ++g)
    {
        int good;
        good = 1;
        for (size_t i = 0; i < I->width; ++i)
        {
            if ((input[i]) & (~(ROW(g,I)[i])))
            {
                good = 0;
                break;
            }
        }
        if (good)
        {
            for (size_t i = 0; i < I->width; ++i)
            {
                output[i] &= ROW(g,I)[i];
            }
        }
    }
}
int countConceptsInBulk (FormalConceptIntentBulkList root)
use this for bulks that are filled in order
Parameters:
root
Returns:
number of concepts in bulk
Definition at line 393 of file fca.c.
References sFormalConceptIntentBulkNode::chunks, CHUNKSIZE, sFormalConceptIntentBulkNode::next, RETURN_ZERO_IF_ZERO, smyFormalConceptIntentChunk::size, and sFormalConceptIntentBulkNode::size.
Referenced by main(), and writeConceptsToFile().
{
    RETURN_ZERO_IF_ZERO(root);
    int count = 0;
    while (root != 0)
    {
        if (root->size > 0)
        {
            /*
             * count the full chunks
             */
            count += CHUNKSIZE * (root->size - 1);
            /*
             * and the last chunk
             */
            count += root->chunks[root->size - 1]->size;
        }
        root = root->next;
    }
    return count;
}
size_t countConceptsInBulkV (FormalConceptIntentBulkListV root)
use this for bulks that are filled in order
Parameters:
root
Returns:
number of concepts in bulk
count the full chunks
and the last chunk
Definition at line 802 of file fcaV.c.
References sFormalConceptIntentBulkNodeV::chunks, CHUNKSIZEV, sFormalConceptIntentBulkNodeV::next, RETURN_ZERO_IF_ZERO, smyFormalConceptIntentChunkV::size, and sFormalConceptIntentBulkNodeV::size.
Referenced by main(), and writeConceptsToFileV().
{
    RETURN_ZERO_IF_ZERO(root);
    size_t count = 0;
    while (root != 0)
    {
        if (root->size > 0)
        {
            count += CHUNKSIZEV * (root->size - 1);
            count += root->chunks[root->size - 1]->size;
        }
        root = root->next;
    }
    return count;
}
void deleteConceptBulk (FormalConceptIntentBulkList * rootNode)
deletes the entire bulk list
Parameters:
rootNode pointer to the first node
Definition at line 361 of file fca.c.
References sFormalConceptIntentBulkNode::chunks, deleteConceptChunk(), sFormalConceptIntentBulkNode::next, RETURN_IF_ZERO, and sFormalConceptIntentBulkNode::size.
Referenced by main().
{
    RETURN_IF_ZERO(rootNode);
    RETURN_IF_ZERO(*rootNode);
    FormalConceptIntentBulkList l;
    l = *rootNode;
    *rootNode = 0;
    do
    {
        for (int var = 0; var < l->size; ++var)
        {
            deleteConceptChunk(&(l->chunks[var]));
        }
        FormalConceptIntentBulkList next;
        next = l->next;
        free(l->chunks);
        free(l);
        l = next;
    } while (l != 0);
}
void deleteConceptBulkV (FormalConceptIntentBulkListV * rootNode)
deletes the entire bulk list
Parameters:
rootNode pointer to the first node
Definition at line 770 of file fcaV.c.
References sFormalConceptIntentBulkNodeV::chunks, deleteConceptChunkV(), sFormalConceptIntentBulkNodeV::next, RETURN_IF_ZERO, and sFormalConceptIntentBulkNodeV::size.
Referenced by main().
{
    RETURN_IF_ZERO(rootNode);
    RETURN_IF_ZERO(*rootNode);
    FormalConceptIntentBulkListV l;
    l = *rootNode;
    *rootNode = 0;
    do
    {
        for (size_t var = 0; var < l->size; ++var)
        {
            deleteConceptChunkV(&(l->chunks[var]));
        }
        FormalConceptIntentBulkListV next;
        next = l->next;
        free(l->chunks);
        free(l);
        l = next;
    } while (l != 0);
}
void deleteConceptChunk (myFormalConceptIntentChunk ** c)
deletes a concept chunk object and sets its pointer to zero
Parameters:
c pointer to the concept chunk to be deleted
Definition at line 326 of file fca.c.
References RETURN_IF_ZERO.
Referenced by deleteConceptBulk().
{
    RETURN_IF_ZERO(c);
    RETURN_IF_ZERO(*c);
    free((*c)->incidence);
    free(*c);
    *c = 0;
}
void deleteConceptChunkV (myFormalConceptIntentChunkV ** c)
deletes a concept chunk object and sets its pointer to zero
Parameters:
c pointer to the concept chunk to be deleted
Definition at line 539 of file fcaV.c.
References RETURN_IF_ZERO.
Referenced by deleteConceptBulkV().
{
    RETURN_IF_ZERO(c);
    RETURN_IF_ZERO(*c);
    free((*c)->incidence);
    free(*c);
    *c = 0;
}
int intentCmp (int attributes, const IncidenceCell * minus, const IncidenceCell * plus)
compare two intent vectors
Parameters:
attributes attribute count
minus "left" operand
plus "right" operand
Returns:
-1 if minus is bigger, 1 if plus is bigger, 0 if minus and plus is the same
Definition at line 591 of file fca.c.
References INCIDES.
{
    for (int var = 0; var < attributes; ++var)
    {
        if (INCIDES(minus[var]))
        {
            if (!INCIDES((plus[var])))
                return -1;
        }
        else if (INCIDES(plus[var]))
        {
            return 1;
        }
    }
    return 0;
}
int intentCmpV (size_t attributes, const IncidenceVector minus, const IncidenceVector plus)
compare two intent vectors
Parameters:
attributes attribute count
minus "left" operand
plus "right" operand
Returns:
-1 if minus is bigger, 1 if plus is bigger, 0 if minus and plus is the same
in this case, OFFSET(attributes) == OFFSET(attributes-1)
we only check the lower bits 0 through (attributes-1)
ELSE: attributes has 64 as factor, so we have done all necessary comparisons in the first loop.
Definition at line 468 of file fcaV.c.
References BITNBR, CRIMPVALUE, and OFFSET.
Referenced by nextClosureVX1().
{
    for (size_t var = 0; var < OFFSET(attributes); ++var)
    {
        if (minus[var] > plus[var])
            return -1;
        if (plus[var] > minus[var])
            return 1;
    }
    if (BITNBR(attributes))
    {
        uint64_t l, r;
        l = minus[OFFSET(attributes)] & CRIMPVALUE(attributes-1);
        r = plus[OFFSET(attributes)] & CRIMPVALUE(attributes-1);
        if (l > r)
            return -1;
        if (r > l)
            return 1;
    }
    return 0;
}
FormalConceptIntentBulkList newConceptBulk (int attributes)
creates a new formal concept intent bulk list
Parameters:
attributes number of attributes of the concept intents
Returns:
new formal concept intent bulk list's first node
Definition at line 344 of file fca.c.
References sFormalConceptIntentBulkNode::attributes, BULKSIZE, sFormalConceptIntentBulkNode::chunks, sFormalConceptIntentBulkNode::next, and sFormalConceptIntentBulkNode::size.
Referenced by addConceptToBulk(), and newConceptBulkFromContext().
{
    FormalConceptIntentBulkList l;
    l = malloc(sizeof(struct sFormalConceptIntentBulkNode));
    l->attributes = attributes;
    l->size = 0;
    l->chunks = calloc(BULKSIZE, sizeof(myFormalConceptIntentChunk*));
    l->next = 0;
    return l;
}
FormalConceptIntentBulkList newConceptBulkFromContext (FormalContext ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
Parameters:
ctx formal context
Returns:
concept intents
Definition at line 616 of file fca.c.
References addConceptToBulk(), smyFormalContext::attributes, CLEAR, closeIntent(), CROSS, INCIDES, newConceptBulk(), and RETURN_ZERO_IF_ZERO.
Referenced by main().
{
    RETURN_ZERO_IF_ZERO(ctx);
    myFormalContext *c;
    c = (myFormalContext*) ctx;
    IncidenceCell *M;
    IncidenceCell *Y;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    Y = calloc(c->attributes, sizeof(IncidenceCell));
    M = malloc(c->attributes * sizeof(IncidenceCell));
#pragma GCC diagnostic pop
    /*
     * calculate the bottom intent of the concept lattice, i.e. {}''
     */
    closeIntent(ctx, Y, M);
    FormalConceptIntentBulkList root;
    FormalConceptIntentBulkList last;
    root = newConceptBulk(c->attributes);
    /*
     * add the bottom element of the concept lattice (a concept lattice is never empty)
     */
    last = addConceptToBulk(root, M);
    /*
     * begin of nextClosure function iteration
     */
    nextClosure:
    for (int i = c->attributes - 1; i >= 0; --i)
    {
        if (!INCIDES(M[i]))
        {
            CROSS(M[i]);
            closeIntent(ctx, M, Y);
            int good;
            good = 1;
            for (int j = 0; j < i; ++j)
            {
                if (INCIDES(Y[j]))
                {
                    if (!INCIDES((M[j])))
                    {
                        good = 0;
                        break;
                    }
                }
            }
            if (good)
            {
                /*
                 * we found the next intent
                 */
                last = addConceptToBulk(last, Y);
                /*
                 * continue with Y for M
                 */
                IncidenceCell *DELTA;
                DELTA = M;
                M = Y;
                Y = DELTA;
                /*
                 * do the nextClosure
                 */
                goto nextClosure;
            }
        }
        CLEAR(M[i]);
    }
    /*
     * free up memory
     */
    free(M);
    free(Y);
    return root;
}
FormalConceptIntentBulkListV newConceptBulkFromContextV (FormalContextV ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
Parameters:
ctx formal context
Returns:
concept intents
calculate the bottom intent of the concept lattice, i.e. {}''
add the bottom element of the concept lattice (a concept lattice is never empty)
begin of nextClosure function iteration
we found the next intent
continue with Y for M
do the nextClosure
free up memory
Definition at line 578 of file fcaV.c.
References addConceptToBulkV(), smyFormalContextV::attributes, CLEARV, closeIntentV(), CRIMPVALUE, CROSSV, INCIDESV, newConceptBulkV(), OFFSET, RETURN_ZERO_IF_ZERO, and smyFormalContextV::width.
Referenced by main().
{
    RETURN_ZERO_IF_ZERO(ctx);
    myFormalContextV *c;
    c = (myFormalContextV*) ctx;
    IncidenceVector M;
    IncidenceVector Y;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    Y = calloc(c->width, sizeof(uint64_t));
    M = malloc(c->width * sizeof(uint64_t));
#pragma GCC diagnostic pop
    closeIntentV(ctx, Y, M);
    FormalConceptIntentBulkListV root;
    FormalConceptIntentBulkListV last;
    root = newConceptBulkV(c->attributes);
    last = addConceptToBulkV(root, M);
    nextClosure:
    for (size_t i = c->attributes; i > 0;)
    {
        --i;
        if (!INCIDESV(M,i))
        {
            CROSSV(M, i);
            closeIntentV(ctx, M, Y);
            int good;
            good = 1;
            for (unsigned int j = 0; j < OFFSET(i); ++j)
            {
                if (Y[j] & (~(M[j])))
                {
                    good = 0;
                    break;
                }
            }
            if (good)
            {
                if (Y[OFFSET(i)] & (~M[OFFSET(i)]) & CRIMPVALUE(i))
                {
                    good = 0;
                }
            }
            if (good)
            {
                last = addConceptToBulkV(last, Y);
                IncidenceVector DELTA;
                DELTA = M;
                M = Y;
                Y = DELTA;
                goto nextClosure;
            }
        }
        CLEARV(M, i);
    }
    free(M);
    free(Y);
    return root;
}
FormalConceptIntentBulkListV newConceptBulkV (size_t attributes)
creates a new formal concept intent bulk list
Parameters:
attributes number of attributes of the concept intents
Returns:
new formal concept intent bulk list's first node
Definition at line 557 of file fcaV.c.
References sFormalConceptIntentBulkNodeV::attributes, BULKSIZEV, sFormalConceptIntentBulkNodeV::chunks, sFormalConceptIntentBulkNodeV::next, sFormalConceptIntentBulkNodeV::size, WIDTH, and sFormalConceptIntentBulkNodeV::width.
Referenced by addConceptToBulkV(), newConceptBulkFromContextV(), and nextClosureVX1().
{
    FormalConceptIntentBulkListV l;
    l = malloc(sizeof(struct sFormalConceptIntentBulkNodeV));
    l->attributes = attributes;
    l->width = WIDTH(attributes);
    l->size = 0;
    l->chunks = calloc(BULKSIZEV, sizeof(myFormalConceptIntentChunkV*));
    l->next = 0;
    return l;
}
myFormalConceptIntentChunk* newConceptChunk (int attributes)
create a new formal concept chunk
Parameters:
attributes number of attributes of the hosting formal context
Returns:
a new concept chunk object
Definition at line 303 of file fca.c.
References smyFormalConceptIntentChunk::attributes, CHUNKSIZE, smyFormalConceptIntentChunk::incidence, and smyFormalConceptIntentChunk::size.
Referenced by addConceptToBulk().
{
    myFormalConceptIntentChunk *c;
    c = malloc(sizeof(myFormalConceptIntentChunk));
    c->attributes = attributes;
    c->size = 0;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    c->incidence = calloc(attributes * CHUNKSIZE, sizeof(IncidenceCell));
#pragma GCC diagnostic pop
    return c;
}
myFormalConceptIntentChunkV* newConceptChunkV (size_t attributes)
create a new formal concept chunk
Parameters:
attributes number of attributes of the hosting formal context
Returns:
a new concept chunk object
Definition at line 511 of file fcaV.c.
References smyFormalConceptIntentChunkV::attributes, sFormalConceptIntentBulkNodeV::attributes, CHUNKSIZEV, smyFormalConceptIntentChunkV::incidence, smyFormalConceptIntentChunkV::size, WIDTH, and smyFormalConceptIntentChunkV::width.
Referenced by addConceptToBulkV().
{
    myFormalConceptIntentChunkV *c;
    c = malloc(sizeof(myFormalConceptIntentChunkV));
    c->attributes = attributes;
    c->width = WIDTH(attributes);
    c->size = 0;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
    c->incidence = calloc(c->width * CHUNKSIZEV, sizeof(uint64_t));
#pragma GCC diagnostic pop
    return c;
}
FormalConceptIntentBulkListV nextClosureVX (FormalContextV ctx)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm
Parameters:
N number of threads
ctx formal context
Returns:
concept intents
Definition at line 204 of file fcaVnextClosureX.c.
References smyFormalContextV::attributes, callNextClosureVX1(), CROSSV, snextClosureVX1Params::ctx, sFormalConceptIntentBulkNodeV::next, nextClosureVX1(), RETURN_ZERO_IF_ZERO, snextClosureVX1Params::rVal, snextClosureVX1Params::start, snextClosureVX1Params::stop, and smyFormalContextV::width.
Referenced by main().
{
    RETURN_ZERO_IF_ZERO(ctx);
    myFormalContextV *c;
    c = (myFormalContextV*) ctx;
    size_t N;
    N = 1;
    if (c->attributes >= 3)
        N = 8;
    else if (c->attributes >= 2)
        N = 4;
    else if (c->attributes >= 1)
        N = 2;
    if (N < 2)
        return nextClosureVX1(ctx, 0, 0);
    IncidenceVector bounds;
    bounds = calloc(c->width * (N - 1), sizeof(uint64_t));
    if (N == 2)
    {
        CROSSV(bounds, 0);
    }
    else if (N == 4)
    {
        CROSSV(bounds, 1); //01
        CROSSV(bounds + c->width, 0); //10
        CROSSV(bounds + c->width * 2, 1); //11
        CROSSV(bounds + c->width * 2, 0);
    }
    else if (N == 8)
    {
        CROSSV(bounds, 2); // 001
        CROSSV(bounds + c->width, 1); //010
        CROSSV(bounds + c->width * 2, 2); //011
        CROSSV(bounds + c->width * 2, 1);
        CROSSV(bounds + c->width * 3, 0); //100
        CROSSV(bounds + c->width * 4, 0); //101
        CROSSV(bounds + c->width * 4, 2);
        CROSSV(bounds + c->width * 5, 1); //110
        CROSSV(bounds + c->width * 5, 0);
        CROSSV(bounds + c->width * 6, 0); //111
        CROSSV(bounds + c->width * 6, 1);
        CROSSV(bounds + c->width * 6, 2);
    }
//  for (int i = 0; i < N - 1; ++i)
//  {
//      printf("BOUND %16llx\n", *(bounds + i * c->width)&CRIMPVALUE(c->attributes-1));
//      if (i > 0)
//          printf("CMP %d\n",
//                  intentCmpV(c->attributes, bounds + (i - 1) * c->width,
//                          bounds + i * c->width));
//  }
    nextClosureVX1Params chunks;
    chunks = malloc(N * sizeof(struct snextClosureVX1Params));
    pthread_t *threads;
    threads = malloc(N * sizeof(pthread_t));
    for (size_t i = 0; i < N; ++i)
    {
        chunks[i].ctx = ctx;
        if (i > 0)
            chunks[i].start = (bounds + c->width * (i - 1));
        else
            chunks[i].start = 0;
        if (i < N - 1)
            chunks[i].stop = (bounds + c->width * (i));
        else
            chunks[i].stop = 0;
    }
    for (size_t i = 0; i < N; ++i)
    {
        pthread_create(&threads[i], 0, callNextClosureVX1, (void*) &chunks[i]);
    }
    for (size_t i = 0; i < N; ++i)
    {
        pthread_join(threads[i], 0);
    }
//  for (size_t i = 0; i < N; ++i)
//  {
//      printf("%zu thread: counts %zu\n", i,
//              countConceptsInBulkV(chunks[i].rVal));
//  }
    FormalConceptIntentBulkListV root;
    FormalConceptIntentBulkListV last;
    root = chunks[0].rVal;
    last = root;
    for (size_t var = 1; var < N; ++var)
    {
        while (last->next)
            last = last->next;
        last->next = chunks[var].rVal;
    }
    free(bounds);
    free(chunks);
    return root;
}
FormalConceptIntentBulkListV nextClosureVX1 (FormalContextV ctx, const IncidenceVector start, const IncidenceVector stop)
creates a new formal concept intent chunk and fills it with the intents of all formal concepts in the concept lattice of ctx, using next closure algorithm, that are in a given lexicographic interval of the powerset
Parameters:
ctx formal context
start first attribute vector (not included if it is a concept intent) if this is zero, start with M={}, in this case, we add the bottom concept in case of M''=={}
stop last attribute vector, or zero to continue until the end
Returns:
concept intents between (start, stop]
calculate the bottom intent of the concept lattice, i.e. {}''
add the bottom element of the concept lattice (a concept lattice is never empty)
begin of nextClosure function iteration
check whether we are still in range
the (pseudo)intent Y is bigger than stop
we found the next intent
continue with Y for M
do the nextClosure
free up memory
Definition at line 52 of file fcaVnextClosureX.c.
References addConceptToBulkV(), smyFormalContextV::attributes, CLEARV, closeIntentV(), CRIMPVALUE, CROSSV, INCIDESV, intentCmpV(), newConceptBulkV(), OFFSET, RETURN_ZERO_IF_ZERO, and smyFormalContextV::width.
Referenced by callNextClosureVX1(), and nextClosureVX().
{
    RETURN_ZERO_IF_ZERO(ctx);
    myFormalContextV *c;
    c = (myFormalContextV*) ctx;
    IncidenceVector M;
    IncidenceVector Y;
    Y = calloc(c->width, sizeof(uint64_t));
    M = malloc(c->width * sizeof(uint64_t));
    FormalConceptIntentBulkListV root;
    FormalConceptIntentBulkListV last;
    root = newConceptBulkV(c->attributes);
    if (start)
    {
        memcpy(M, start, c->width * sizeof(uint64_t));
        last = root;
    }
    else
    {
        closeIntentV(ctx, Y, M);
        last = addConceptToBulkV(root, M);
    }
    nextClosure:
    for (size_t i = c->attributes; i > 0;)
    {
        --i;
        if (!INCIDESV(M,i))
        {
            CROSSV(M, i);
            closeIntentV(ctx, M, Y);
            int good;
            good = 1;
            for (unsigned int j = 0; j < OFFSET(i); ++j)
            {
                if (Y[j] & (~(M[j])))
                {
                    good = 0;
                    break;
                }
            }
            if (good)
            {
                if (Y[OFFSET(i)] & (~M[OFFSET(i)]) & CRIMPVALUE(i))
                {
                    good = 0;
                }
            }
            if (good)
            {
                if (stop)
                {
                    if (intentCmpV(c->attributes, Y, stop) < 0)
                    {
                        goto gracefulReturn;
                    }
                }
                last = addConceptToBulkV(last, Y);
                IncidenceVector DELTA;
                DELTA = M;
                M = Y;
                Y = DELTA;
                goto nextClosure;
            }
        }
        CLEARV(M, i);
    }
    gracefulReturn:
    free(M);
    free(Y);
    return root;
}
void writeConceptsToFile (FormalContext ctx, FormalConceptIntentBulkList root, const char * filename)
write a list of concept intents into a .cxt file
Parameters:
ctx formal context (or 0, is used for attribute names)
root the first node of the formal concept intent bulk
filename output file name (.cxt)
Definition at line 720 of file fca.c.
References smyFormalContext::attributeNames, smyFormalContext::attributes, sFormalConceptIntentBulkNode::attributes, sFormalConceptIntentBulkNode::chunks, countConceptsInBulk(), gIm, sFormalConceptIntentBulkNode::next, RETURN_IF_ZERO, smyFormalConceptIntentChunk::size, sFormalConceptIntentBulkNode::size, and WARN_IF_UNEQUAL_DO.
Referenced by main().
{
    RETURN_IF_ZERO(root);
    myFormalContext* c;
    if (ctx != 0)
    {
        c = (myFormalContext*) ctx;
        WARN_IF_UNEQUAL_DO(c->attributes, root->attributes, c = 0);
    }
    else
    {
        c = 0;
    }
    RETURN_IF_ZERO(filename);
    FILE* file;
    file = fopen(filename, "w");
    RETURN_IF_ZERO(file);
    int objects;
    objects = countConceptsInBulk(root);
    fprintf(file, "B\n\n%d\n%d\n\n", objects, root->attributes);
    for (int var = 0; var < objects; ++var)
    {
        fprintf(file, "C%8d\n", (var + 1));
    }
    if (c != 0)
    {
        for (int var = 0; var < c->attributes; ++var)
        {
            fputs(c->attributeNames[var], file);
            fputs("\n", file);
        }
    }
    else
    {
        for (int var = 0; var < root->attributes; ++var)
        {
            fprintf(file, "m%8d\n", (var + 1));
        }
    }
    for (; root != 0; root = root->next)
    {
        for (int chunk = 0; chunk < root->size; ++chunk)
        {
            for (int g = 0; g < root->chunks[chunk]->size; ++g)
            {
                for (int m = 0; m < root->attributes; ++m)
                {
                    if ( gIm(g, root->chunks[chunk], m))
                        fputs("X", file);
                    else
                        fputs(".", file);
                }
                fputs("\n", file);
            }
        }
    }
    fclose(file);
}
void writeConceptsToFileV (FormalContextV ctx, FormalConceptIntentBulkListV root, const char * filename)
write a list of concept intents into a .cxt file
Parameters:
ctx formal context (or 0, is used for attribute names)
root the first node of the formal concept intent bulk
filename output file name (.cxt)
Definition at line 693 of file fcaV.c.
References smyFormalContextV::attributeNames, smyFormalContextV::attributes, sFormalConceptIntentBulkNodeV::attributes, sFormalConceptIntentBulkNodeV::chunks, countConceptsInBulkV(), INCIDESV, sFormalConceptIntentBulkNodeV::next, RETURN_IF_ZERO, ROW, smyFormalConceptIntentChunkV::size, sFormalConceptIntentBulkNodeV::size, and WARN_IF_UNEQUAL_DO.
Referenced by main().
{
    RETURN_IF_ZERO(root);
    myFormalContextV* c;
    if (ctx != 0)
    {
        c = (myFormalContextV*) ctx;
        WARN_IF_UNEQUAL_DO(c->attributes, root->attributes, c = 0);
    }
    else
    {
        c = 0;
    }
    RETURN_IF_ZERO(filename);
    FILE* file;
    file = fopen(filename, "w");
    RETURN_IF_ZERO(file);
    size_t objects;
    objects = countConceptsInBulkV(root);
    fprintf(file, "B\n\n%zu\n%zu\n\n", objects, root->attributes);
    for (size_t var = 0; var < objects; ++var)
    {
        fprintf(file, "C%8zu\n", (var + 1));
    }
    if (c != 0)
    {
        for (size_t var = 0; var < c->attributes; ++var)
        {
            fputs(c->attributeNames[var], file);
            fputs("\n", file);
        }
    }
    else
    {
        for (size_t var = 0; var < root->attributes; ++var)
        {
            fprintf(file, "m%8zu\n", (var + 1));
        }
    }
    for (; root != 0; root = root->next)
    {
        for (size_t chunk = 0; chunk < root->size; ++chunk)
        {
            for (size_t g = 0; g < root->chunks[chunk]->size; ++g)
            {
                for (size_t m = 0; m < root->attributes; ++m)
                {
                    if (INCIDESV(ROW(g, root->chunks[chunk]), m))
                        fputs("X", file);
                    else
                        fputs(".", file);
                }
                fputs("\n", file);
            }
        }
    }
    fclose(file);
}